# Generated by Django 5.0.7 on 2024-08-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_avatar_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_follower',
            new_name='follower',
        ),
    ]
