# Generated by Django 5.0.7 on 2024-08-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_user_follower_follow_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
